### ISSUE TITLE
Additional libs

### ISSUE THREAD

**Issue by yerzhanm** [WowzaMediaSystems/wse-plugin-s3upload#2]
Hi, you need add to readme file about additional libs that need to be added to wowza lib.
After adding this libs this module works

> http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-kms/1.10.77/aws-java-sdk-kms-1.10.77.jar
> http://central.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
> http://central.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
> http://central.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar
> http://central.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar
> http://central.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.5.3/jackson-dataformat-cbor-2.5.3.jar
> http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.5.0/jackson-annotations-2.5.0.jar
> http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.5.3/jackson-databind-2.5.3.jar
> http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.jar

May be some of them already in wowza lib.

**Comment by rogerlittin** [comment]
Hi,

Thank's for the info. We have had users report issues in the past but haven't been able to narrow it down to a specific package.  When the module was first released, 1.10 was the current AWS version and everything worked fine. After they updated to 1.11, it broke because aws is dependent on a later version of http client than the one that ships with Wowza.  I've never had an issue running the module with the packages we suggested but It could be because I've been using an old set of credentials.  I could see where kms may be needed if you are using newer credentials, especially for some of the newer locations.

For the rest of the packages, most of these are included with The server installation so probably aren't needed and may conflict with the installed versions.

If possible, can you test just with the aws-java-sdk-kms package and not with the other packages you suggest.

Thanks,

Roger.

**Comment by yerzhanm** [comment]
Yes, it works only with aws-java-sdk-kms.

**Comment by yerzhanm** [comment]
Finally, u need aws-java-sdk-s3, aws-java-sdk-core, aws-java-sdk-kms

**Comment by rogerlittin** [comment]
Thanks,

I'll update the README.

As a point of interest, which location is you S3 bucket located in?

Thanks,

Roger.

**Comment by yerzhanm** [comment]
Its another issue))
we get error with Sig v4. changed bucket to us-east-1. So, It will be
better if u add configuration for region.

**Comment by rogerlittin** [comment]
Ok, I'll look into it. I was aware that newer regions are V4 only but I wasn't aware that you could specify a region in our case. Because we are just uploading (and not actually creating the bucket) I didn't think there was a need to specify the region.

Thanks again.

-Roger.

**Comment by yerzhanm** [comment]
I used ap-south-1.
U'll get error when checking for existence of bucket.

**Comment by rogerlittin** [comment]
Thanks, I'll check it out.

-Roger

**Comment by rogerlittin** [comment]
I've updated the module to be able to set the endpoint for V4 authentication. It is only actually required for locations that only support V4 and is optional for other locations. It does appear that there was an issue when actually trying to upload to one of these new locations. I had to set the endpoint rather than the region because the regions are hard coded on the SDK and this version doesn't contain the latest ones. To set the endpoint, add a property to the Application.xml called `s3UploadEndpoint` and set it to [S3 Endpoints](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region)

**Comment by rogerlittin** [comment]
I also updated the bucket detection code to make sure the user is allowed to access the bucket before trying to upload. It appears that the call to check if a bucket exists does any validation on the user but it did fail if an endpoint wasn't set ad the bucket is in a V4 region.
