### ISSUE TITLE
Replacing existing files with same name

### ISSUE THREAD

**Issue by thoste** [WowzaMediaSystems/wse-plugin-s3upload#5]
When streaming a stream "myStream", this gets recorded as myStream.mp4 and uploaded to S3. When a new stream with the same name gets recorded, it is recorded as myStream.mp4, and the original is moved to myStream_0.mp4 locally, but the original file on S3 is overwritten with the new stream. Would it be possible to rename the file on S3 as well to myStream_0.mp4 before uploading the new myStream.mp4 file to S3? To basically do the same on S3 as you do locally on the server.

**Comment by rogerlittin** [comment]
Hi,

This is a feature that we are working on. It's not straight forward because we do have to remotely rename the files which with S3 is actually a copy & delete operation. With small files it's fairly quick but with large files, it can take some time so I need to make sure there are no performance issues or cases where files are lost.

The way you're describing your problem, it sounds like you are probably using the Record All Streams option in the application configuration (live-record stream type). This option is very restrictive and doesn't allow for custom naming or versioning. The versioning works by renaming the existing file and creating the new recording with the original name.

An alternative option that gives you more control is to use the [LiveStreamAutoRecord module](https://github.com/WowzaMediaSystems/wse-plugin-autorecord). This module uses the Stream Recorder properties so you can define your own naming convention and with versioning, it renames the new recording instead of renaming the old recording. It also as options to define name patterns for what will be recorded so you don end up recording files that you don't want to.

Regards,

Roger

**Comment by thoste** [comment]
Thank you for the response. It sounds like LiveStreamAutoRecord module can solve my issues for now, I'll have a look into it!
